services:
  - type: web
    name: hasmukh-portfolio
    runtime: python
    buildCommand: bash build.sh
    startCommand: cd portfolio && gunicorn portfolio.wsgi:application
    healthCheckPath: /
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECURE_SSL_REDIRECT
        value: "True"
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: SEED_PORTFOLIO
        value: "false"
      - key: CREATE_SUPERUSER
        value: "false"
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
