# Generated by Django 6.0.4 on 2026-05-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallary',
            options={'verbose_name_plural': 'Image Gallaries'},
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
